excluded:
- Pods
- TodoApplicationTests
- TodoApplicationUITests

opt_in_rules:

- multiline_arguments
- multiline_parameters
- vertical_parameter_alignment_on_call
- required_enum_case
- force_unwrapping
- implicitly_unwrapped_optional
- first_where
- overridden_super_call
- prohibited_super_call
- private_over_fileprivate
- redundant_type_annotation
- line_length
- sorted_first_last
- vertical_parameter_alignment
- empty_count
- unneeded_parentheses_in_closure_argument
- closure_end_indentation
- closure_spacing
- literal_expression_end_indentation
- explicit_init
- implicit_return
- number_separator
- operator_usage_whitespace
- redundant_nil_coalescing
- sorted_imports
- untyped_error_in_catch
- function_body_length
- type_body_length
- file_length
- cyclomatic_complexity
- closure_parameter_position
- conditional_returns_on_newline
- function_default_parameter_at_end
- trailing_closure

disabled_rules:

- void_return

# configurations

line_length: 120
